version: "3"
services:
  coredb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - db:/data/db
  web:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - ${PORT}:4000
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=coredb
      - DB_NAME=${DB_NAME}
      - PORT=${PORT}
      - MONGO_PORT=${MONGO_PORT} 
    depends_on:
      - coredb
volumes:
  db: